### ISSUE TITLE
Record IDs

### ISSUE THREAD

**Issue by davidmpye** [jwhiddon/EDB#13]
Hi!

I've been doing a bit more EDB related work, and have hit a small issue, which is probably more of a design issue.

EDB's record numbers start from 1, which makes sense from one angle, but is quite different logic from the usual C style arrays, which of course start from element 0.

I've made a patch which changes this behaviour and wonder whether it's the sort of thing you'd be interested in accepting upstream, or whether the current design is your preferred aesthetic :-)

Cheers

David

**Comment by jwhiddon** [comment]
Hi, David.

Most databases start records from 1 so I think that makes the most sense in
our situation as well.  Maybe we could define a constant that lets the user
select 1 or 0?  I agree, this would be easier than array[n+1] in your
situation.

Thanks,

James

**Comment by davidmpye** [comment]
Hi,

That's fair enough, it was just something that seemed odd to me because my
main experience of data structures has been C-style arrays etc.

I'll manage with the numbering as it is :-)

Regards

David
