### ISSUE TITLE
db.open() function returns Zero

### ISSUE THREAD

**Issue by himanshu-hearthacker** [jwhiddon/EDB#30]
I want to create table only once in life time. I am using this function to detect if table exists or not. But this function always returns me 0(Zero) every time even if table exists or not.
get this updated open() function  from here..
https://github.com/firebull/arduino-edb/blob/master/EDB.cpp

    EDB_Status result = db.open(0);
    if (result == EDB_ERROR) {
            Serial.println("Creating DB " + String(0));
            db.create(0, TABLE_SIZE, sizeof(LogEvent));
  }
   else{
        Serial.println(result);
      }

**Comment by rnsi** [comment]
[himanshu-hearthacker]- I know it's been a while, but did you ever resolve this? What was your workaround?
