### ISSUE TITLE
MMC card

### ISSUE THREAD

**Issue by sompret** [jwhiddon/EDB#9]
Hi,
Could you give me an example for using SD card as data location? I'm using Arduino Ethernet Shield R.3 as SD card reader. thanks

**Comment by jwhiddon** [comment]
I don't have the hardware to do that.  If someone has the hardware, hopefully they will contribute an example.

**Comment by joscha** [comment]
There is an example here: https://github.com/firebull/arduino-edb/blob/master/examples/EDB_SDCARD/EDB_SDCARD.pde - the author also made some other fixes to the EDB code (@jwhiddon, do you think some of those things should be ported back?) but the example should run fine with the code from this repository.

**Comment by jwhiddon** [comment]
I'll take a look and incorporate the changes.  Thanks for letting me know!

**Comment by joscha** [comment]
fixed via f87bc6ac29f955358ddcd3b0a9f1beac7114a23f
